name: car_mate
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  animated_custom_dropdown: ^3.1.1
  cached_network_image: ^3.4.1
  connectivity_plus: ^6.1.3
  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  device_info_plus: ^11.3.0
  dio: ^5.7.0
  dotted_border: ^2.0.0
  easy_localization: ^3.0.7
  equatable: ^2.0.5
  firebase_core: ^3.9.0
  firebase_messaging: ^15.1.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_bounceable: ^1.2.0
  flutter_rating: ^2.0.2
  flutter_screenutil: ^5.9.0
  flutter_spinkit: ^5.2.1
  flutter_svg: ^2.0.16
  get_it: ^7.2.0
  google_generative_ai: ^0.4.6
  google_nav_bar: ^5.0.7
  http: ^1.3.0
  http_parser: ^4.1.2
  image_picker: ^0.8.7+4
  page_transition: ^2.1.0
  permission_handler: ^11.4.0
  pinput: ^5.0.0
  pretty_dio_logger: ^1.3.1
  shared_preferences: ^2.5.2
  skeletonizer: ^1.4.3
  timeago: ^3.7.0

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/png/
    - assets/svg/
    - assets/images/profile_image.jpg
    - assets/fonts/
    - assets/translations/
    - assets/images/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Bold.ttf
        - asset: assets/fonts/Cairo-Medium.ttf
        - asset: assets/fonts/Cairo-Regular.ttf
          # style: italic
