name: car_mate
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  dio: ^5.7.0
  easy_localization: ^3.0.7
  equatable: ^2.0.5
  firebase_core: ^3.9.0
  firebase_messaging: ^15.1.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_local_notifications: ^18.0.1
  flutter_screenutil: ^5.9.0
  flutter_spinkit: ^5.2.1
  flutter_svg: ^2.0.16
  get_it: ^7.2.0
  google_nav_bar: ^5.0.7
  page_transition: ^2.1.0
  pinput: ^5.0.0
  pretty_dio_logger: ^1.3.1
  shared_preferences: ^2.2.3
  dotted_border: ^2.0.0
  image_picker: ^0.8.7+4
  animated_custom_dropdown: ^3.1.1
  flutter_rating: ^2.0.2

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/svg/
    - assets/fonts/
    - assets/translations/

  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Bold.ttf
        - asset: assets/fonts/Cairo-Medium.ttf
        - asset: assets/fonts/Cairo-Regular.ttf
          # style: italic